CPPFILES=$(SRCDIR)/RegOpt.cpp \
		$(SRCDIR)/RegToolsOpt.cpp \
		$(SRCDIR)/BenchmarkOpt.cpp \
		$(SRCDIR)/CLAIREUtils.cpp \
		$(SRCDIR)/ghost.cpp \
		$(SRCDIR)/interp3.cpp \
		$(SRCDIR)/Interp3_Plan.cpp \
		$(SRCDIR)/VecField.cpp \
		$(SRCDIR)/TenField.cpp \
		$(SRCDIR)/ReadWriteReg.cpp \
		$(SRCDIR)/SynProbRegistration.cpp \
		$(SRCDIR)/TransportProblem.cpp \
		$(SRCDIR)/TransportEquation.cpp \
		$(SRCDIR)/ContinuityEquation.cpp \
		$(SRCDIR)/DistanceMeasure.cpp \
		$(SRCDIR)/DistanceMeasureSL2.cpp \
		$(SRCDIR)/DistanceMeasureSL2aux.cpp \
		$(SRCDIR)/SemiLagrangian.cpp \
		$(SRCDIR)/Optimizer.cpp \
		$(SRCDIR)/KrylovInterface.cpp \
		$(SRCDIR)/TaoInterface.cpp \
		$(SRCDIR)/CLAIREInterface.cpp \
		$(SRCDIR)/MultiLevelPyramid.cpp \
		$(SRCDIR)/Preconditioner.cpp \
		$(SRCDIR)/RegularizationRegistration.cpp \
		$(SRCDIR)/RegularizationRegistrationL2.cpp \
		$(SRCDIR)/RegularizationRegistrationH1.cpp \
		$(SRCDIR)/RegularizationRegistrationH2.cpp \
		$(SRCDIR)/RegularizationRegistrationH1SN.cpp \
		$(SRCDIR)/RegularizationRegistrationH2SN.cpp \
		$(SRCDIR)/RegularizationRegistrationH3.cpp \
		$(SRCDIR)/RegularizationRegistrationH3SN.cpp \
		$(SRCDIR)/OptimizationProblem.cpp \
		$(SRCDIR)/CLAIREBase.cpp \
		$(SRCDIR)/CLAIRE.cpp \
		$(SRCDIR)/CLAIREStokes.cpp \
		$(SRCDIR)/CLAIREDivReg.cpp \
		$(SRCDIR)/Preprocessing.cpp 

CUFILES=$(SRCDIR)/interp3_gpu_new.cu

CPPFILESCUDA=$(SRCDIR)/RegOpt.cpp \
		$(SRCDIR)/RegToolsOpt.cpp \
		$(SRCDIR)/BenchmarkOpt.cpp \
		$(SRCDIR)/CLAIREUtils.cpp \
		$(SRCDIR)/ghost.cpp \
		$(SRCDIR)/interp3.cpp \
		$(SRCDIR)/Interp3_Plan.cpp \
		$(SRCDIR)/VecField.cpp \
		$(SRCDIR)/TenField.cpp \
		$(SRCDIR)/ReadWriteReg.cpp \
		$(SRCDIR)/SynProbRegistration.cpp \
		$(SRCDIR)/TransportProblem.cpp \
		$(SRCDIR)/TransportEquation.cpp \
		$(SRCDIR)/ContinuityEquation.cpp \
		$(SRCDIR)/DistanceMeasure.cpp \
		$(SRCDIR)/DistanceMeasureSL2.cpp \
		$(SRCDIR)/DistanceMeasureSL2aux.cpp \
		$(SRCDIR)/SemiLagrangian.cpp \
		$(SRCDIR)/Optimizer.cpp \
		$(SRCDIR)/KrylovInterface.cpp \
		$(SRCDIR)/TaoInterface.cpp \
		$(SRCDIR)/CLAIREInterface.cpp \
		$(SRCDIR)/MultiLevelPyramid.cpp \
		$(SRCDIR)/Preconditioner.cpp \
		$(SRCDIR)/RegularizationRegistration.cpp \
		$(SRCDIR)/RegularizationRegistrationL2.cpp \
		$(SRCDIR)/RegularizationRegistrationH1.cpp \
		$(SRCDIR)/RegularizationRegistrationH2.cpp \
		$(SRCDIR)/RegularizationRegistrationH1SN.cpp \
		$(SRCDIR)/RegularizationRegistrationH2SN.cpp \
		$(SRCDIR)/RegularizationRegistrationH3.cpp \
		$(SRCDIR)/RegularizationRegistrationH3SN.cpp \
		$(SRCDIR)/OptimizationProblem.cpp \
		$(SRCDIR)/CLAIREBase.cpp \
		$(SRCDIR)/CLAIRE.cpp \
		$(SRCDIR)/CLAIREStokes.cpp \
		$(SRCDIR)/CLAIREDivReg.cpp \
		$(SRCDIR)/Preprocessing.cpp \
		$(SRCDIR)/SemiLagrangianGPUNew.cpp
