INCLUDE(ExternalProject)

# define path for external libraries
SET(COLD_EXTERNAL_LIBDIR "${CMAKE_CURRENT_BINARY_DIR}/external")


##################################
# FFTW
##################################
SET(COLD_FFTW_DIR "${COLD_EXTERNAL_LIBDIR}/fftw")
SET(ENV{FFTW_DIR} "${COLD_FFTW_DIR}")
SET(ENV{FFTW_INCLUDES} "${COLD_FFTW_DIR}/build/include")
SET(ENV{FFTW_LIBRARIES} "${COLD_FFTW_DIR}/build/lib")
SET(COLD_FFTW_VERSION 3.3.4)
SET(COLD_FFTW_MD5 "2edab8c06b24feeb3b82bbb3ebf3e7b3")

MESSAGE( STATUS "COLD_FFTW_DIR: " ${COLD_FFTW_DIR} )

IF(NOT COLD_FFTW_LIBPRJ)

    EXTERNALPROJECT_ADD(COLD_FFTW_LIBPRJ
      #URL ftp://ftp.fftw.org/pub/fftw/fftw-${COLD_FFTW_VERSION}.tar.gz
      URL ${COLD_SOURCE_DIR}/external/fftw-3.3.4.tar.gz
      URL_MD5 ${COLD_FFTW_MD5}
      SOURCE_DIR ${COLD_FFTW_DIR}/src
      BINARY_DIR ${COLD_FFTW_DIR}/src
      TMP_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/fftw
      STAMP_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/fftw
      DOWNLOAD_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/fftw
      INSTALL_DIR ${COLD_FFTW_DIR}/build
      UPDATE_COMMAND ""
      CONFIGURE_COMMAND ./configure
            --prefix=${COLD_FFTW_DIR}/build
            --enable-mpi --enable-threads #--enable-shared
            --enable-sse2 --enable-openmp --enable-avx
            CFLAGS=-O3 MAKEINFO=missing
      BUILD_COMMAND make)

    # ACCFFT also needs the float version; we can't make it at once, so
    # we have got to add an additional three steps for the float version
    EXTERNALPROJECT_ADD_STEP(COLD_FFTW_LIBPRJ lfftw-config
      DEPENDEES install
      COMMAND cd ${COLD_FFTW_DIR}/src && ./configure
            --prefix=${COLD_FFTW_DIR}/build
            --enable-mpi --enable-threads #--enable-shared
            --enable-sse2 --enable-openmp --enable-avx
            --enable-float CFLAGS=-O3 MAKEINFO=missing)

    EXTERNALPROJECT_ADD_STEP(COLD_FFTW_LIBPRJ lfftw-build
      DEPENDEES lfftw-config
      COMMAND cd ${COLD_FFTW_DIR}/src && make)

    EXTERNALPROJECT_ADD_STEP(COLD_FFTW_LIBPRJ lfftw-install
      DEPENDEES lfftw-build
      COMMAND cd ${COLD_FFTW_DIR}/src && make install)

ENDIF(NOT COLD_FFTW_LIBPRJ)

## find library
#FIND_LIBRARY(COLD_FFTW_LIB NAMES fftw3 PATHS ${COLD_FFTW_DIR}/build/lib DOC "FFTW libs")
#FIND_LIBRARY(COLD_FFTW_THREADS_LIB NAMES fftw3_threads PATHS ${COLD_FFTW_DIR}/build/lib DOC "FFTW threads libs")
#FIND_LIBRARY(COLD_FFTWF_LIB NAMES fftw3f PATHS ${COLD_FFTW_DIR}/build/lib DOC "FFTWF libs")
#FIND_LIBRARY(COLD_FFTWF_THREADS_LIB NAMES fftw3f_threads PATHS ${COLD_FFTW_DIR}/build/lib DOC "FFTWF threads libs")

LINK_DIRECTORIES(${COLD_FFTW_DIR}/build/lib)

#SET(COLD_FFTW_LIB ${COLD_FFTW_DIR}/build/lib/${CMAKE_SHARED_LIBRARY_PREFIX}fftw3${CMAKE_SHARED_LIBRARY_SUFFIX})
#SET(COLD_FFTW_THREADS_LIB ${COLD_FFTW_DIR}/build/lib/${CMAKE_SHARED_LIBRARY_PREFIX}fftw3_threads${CMAKE_SHARED_LIBRARY_SUFFIX})
#SET(COLD_FFTWF_LIB ${COLD_FFTW_DIR}/build/lib/${CMAKE_SHARED_LIBRARY_PREFIX}fftw3f${CMAKE_SHARED_LIBRARY_SUFFIX})
#SET(COLD_FFTWF_THREADS_LIB ${COLD_FFTW_DIR}/build/lib/${CMAKE_SHARED_LIBRARY_PREFIX}fftw3f_threads${CMAKE_SHARED_LIBRARY_SUFFIX})


SET(COLD_FFTW_LIB ${COLD_FFTW_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}fftw3${CMAKE_STATIC_LIBRARY_SUFFIX})
SET(COLD_FFTW_THREADS_LIB ${COLD_FFTW_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}fftw3_threads${CMAKE_STATIC_LIBRARY_SUFFIX})
SET(COLD_FFTWF_LIB ${COLD_FFTW_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}fftw3f${CMAKE_STATIC_LIBRARY_SUFFIX})
SET(COLD_FFTWF_THREADS_LIB ${COLD_FFTW_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}fftw3f_threads${CMAKE_STATIC_LIBRARY_SUFFIX})


#ADD_LIBRARY(COLD_FFTW_LIB STATIC IMPORTED)
#SET_TARGET_PROPERTIES(COLD_FFTW_LIB PROPERTIES IMPORTED_LOCATION ${COLD_FFTW_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}fftw3${CMAKE_STATIC_LIBRARY_SUFFIX})

#ADD_LIBRARY(COLD_FFTW_THREADS_LIB STATIC IMPORTED)
#SET_TARGET_PROPERTIES(COLD_FFTW_THREADS_LIB PROPERTIES IMPORTED_LOCATION ${COLD_FFTW_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}fftw3_threads${CMAKE_STATIC_LIBRARY_SUFFIX})


#ADD_LIBRARY(COLD_FFTWF_LIB STATIC IMPORTED)
#SET_TARGET_PROPERTIES(COLD_FFTWF_LIB PROPERTIES IMPORTED_LOCATION ${COLD_FFTW_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}fftw3f${CMAKE_STATIC_LIBRARY_SUFFIX})

#ADD_LIBRARY(COLD_FFTWF_THREADS_LIB STATIC IMPORTED)
#SET_TARGET_PROPERTIES(COLD_FFTWF_THREADS_LIB PROPERTIES IMPORTED_LOCATION ${COLD_FFTW_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}fftw3f_threads${CMAKE_STATIC_LIBRARY_SUFFIX})


LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_FFTW_LIB})
LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_FFTW_THREADS_LIB})
LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_FFTWF_LIB})
LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_FFTWF_THREADS_LIB})

LIST(APPEND COLD_EXTERNAL_INCS ${COLD_FFTW_DIR}/build/include)

INCLUDE_DIRECTORIES(${COLD_FFTW_DIR}/build/include)




##################################
# ACCFFT
##################################
SET(COLD_ACCFFT_DIR "${COLD_EXTERNAL_LIBDIR}/accfft")
SET(ENV{ACCFFT_DIR} "${COLD_ACCFFT_DIR}")

MESSAGE( STATUS "COLD_ACCFFT_DIR: " ${COLD_ACCFFT_DIR} )

IF(NOT COLD_ACCFFT_LIBPRJ)
    EXTERNALPROJECT_ADD(COLD_ACCFFT_LIBPRJ
      DEPENDS COLD_FFTW_LIBPRJ 
      #GIT_REPOSITORY git@github.com:amirgholami/accfft.git
      URL ${COLD_SOURCE_DIR}/external/accfft.tar.gz
      SOURCE_DIR ${COLD_ACCFFT_DIR}/src
      BINARY_DIR ${COLD_ACCFFT_DIR}/build
      TMP_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/accfft
      STAMP_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/accfft
      DOWNLOAD_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/accfft
      INSTALL_DIR ${COLD_ACCFFT_DIR}/build
      CMAKE_COMMAND cmake -DCMAKE_INSTALL_PREFIX=${COLD_ACCFFT_DIR}/build
                          -DFFTW_ROOT=${COLD_FFTW_DIR}/build -DFFTW_USE_STATIC_LIBS=true
      BUILD_COMMAND make
      INSTALL_COMMAND make install
      UPDATE_COMMAND "")
ENDIF(NOT COLD_ACCFFT_LIBPRJ)

#ADD_DEPENDENCIES(COLD_ACCFFT_LIBPRJ ${COLD_PNETCDF_LIB})
#ADD_DEPENDENCIES(COLD_ACCFFT_LIBPRJ ${COLD_FFTW_LIB})
#ADD_DEPENDENCIES(COLD_ACCFFT_LIBPRJ ${COLD_FFTW_THREADS_LIB})
#ADD_DEPENDENCIES(COLD_ACCFFT_LIBPRJ ${COLD_FFTWF_LIB})
#ADD_DEPENDENCIES(COLD_ACCFFT_LIBPRJ ${COLD_FFTWF_THREADS_LIB})
#TARGET_LINK_LIBRARIES(COLD_ACCFFT_LIBPRJ ${COLD_PNETCDF_LIB})
#COLD_PNETCDF_LIBPRJ 

#-DPNETCDF_DIR=${COLD_PNETCDF_DIR}/build -DBUILD_SHARED=false
#-DFFTW_USE_STATIC_LIBS=true
#-DBUILD_GPU=false
#-DBUILD_STEPS=false
#


#FIND_LIBRARY(COLD_ACCFFT_LIB NAMES accfft PATHS ${COLD_ACCFFT_DIR}/build/lib DOC "ACCFFT libs")
#FIND_LIBRARY(COLD_ACCFFTUTILS_LIB NAMES accfft_utils PATHS ${COLD_ACCFFT_DIR}/build/lib DOC "ACCFFT libs")
#FIND_PATH(COLD_ACCFFT_INC NAMES "accfft.h" PATHS ${COLD_ACCFFT_DIR}/build/include)

#SET(COLD_ACCFFT_LIB ${COLD_ACCFFT_DIR}/build/lib/${CMAKE_SHARED_LIBRARY_PREFIX}accfft${CMAKE_SHARED_LIBRARY_SUFFIX})
#SET(COLD_ACCFFTUTILS_LIB ${COLD_ACCFFT_DIR}/build/lib/${CMAKE_SHARED_LIBRARY_PREFIX}accfft_utils${CMAKE_SHARED_LIBRARY_SUFFIX})

SET(COLD_ACCFFT_LIB ${COLD_ACCFFT_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}accfft${CMAKE_STATIC_LIBRARY_SUFFIX})
SET(COLD_ACCFFTUTILS_LIB ${COLD_ACCFFT_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}accfft_utils${CMAKE_STATIC_LIBRARY_SUFFIX})

#ADD_LIBRARY(COLD_ACCFFT_LIB STATIC IMPORTED)
#SET_TARGET_PROPERTIES(COLD_ACCFFT_LIB PROPERTIES IMPORTED_LOCATION ${COLD_ACCFFT_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}accfft${CMAKE_STATIC_LIBRARY_SUFFIX})

#ADD_LIBRARY(COLD_ACCFFTUTILS_LIB STATIC IMPORTED)
#SET_TARGET_PROPERTIES(COLD_ACCFFTUTILS_LIB PROPERTIES IMPORTED_LOCATION ${COLD_ACCFFT_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}accfft${CMAKE_STATIC_LIBRARY_SUFFIX})


LINK_DIRECTORIES(${COLD_ACCFFT_DIR}/build/lib)
INCLUDE_DIRECTORIES(${COLD_ACCFFT_DIR}/build/include)
LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_ACCFFT_LIB})
LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_ACCFFTUTILS_LIB})
LIST(APPEND COLD_EXTERNAL_INCS ${COLD_ACCFFT_DIR}/build/include)




##################################
# PETSC
##################################
SET(COLD_PETSC_DIR "${COLD_EXTERNAL_LIBDIR}/petsc")
SET(COLD_PETSC_ARCH "cxx_opt")
SET(ENV{PETSC_DIR} "${COLD_PETSC_DIR}")
SET(ENV{PETSC_ARCH} "${COLD_PETSC_ARCH}")

# download and build petsc
IF(NOT COLD_PETSC_LIBPRJ)
    EXTERNALPROJECT_ADD(COLD_PETSC_LIBPRJ
      #URL http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.7.0.tar.gz
      #GIT_REPOSITORY https://bitbucket.org/petsc/petsc
      URL ${COLD_SOURCE_DIR}/external/petsc-lite-3.7.0.tar.gz
      SOURCE_DIR ${COLD_PETSC_DIR}/${COLD_PETSC_ARC}
      BINARY_DIR ${COLD_PETSC_DIR}/${COLD_PETSC_ARC}
      TMP_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/petsc
      STAMP_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/petsc
      DOWNLOAD_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/petsc
      INSTALL_DIR ${COLD_PETSC_DIR}/${COLD_PETSC_ARC}
      CONFIGURE_COMMAND ./configure PETSC_DIR=${COLD_PETSC_DIR}
                                    PETSC_ARCH=${COLD_PETSC_ARCH}
                                    --with-clanguage=C++
                                    --with-debugging=0 CXXOPTFLAGS=${CMAKE_CXX_FLAGS} COPTFLAGS=${CMAKE_C_FLAGS}
                                    --download-f2cblaslapack --with-shared=0
                                    --with-x=0 --with-64-bit-indices
                                    --with-c++-support=1 --with-pthread=1
                                    --with-cc=${MPI_C_COMPILER} --with-cxx=${MPI_CXX_COMPILER} --with-fc=0
                                    #--with-mpi-dir=/opt/apps/intel14/mvapich2/2.0b
      BUILD_COMMAND make PETSC_DIR=${COLD_PETSC_DIR} PETSC_ARCH=${COLD_PETSC_ARCH} all
      INSTALL_COMMAND "")
ENDIF(NOT COLD_PETSC_LIBPRJ)


## find library
#FIND_LIBRARY(COLD_PETSC_LIB NAMES petsc PATHS ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/lib DOC "PETSC libs")
#SET(COLD_PETSC_LIB ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}petsc${CMAKE_STATIC_LIBRARY_SUFFIX})
#SET(COLD_LAPACK_LIB ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}f2clapack${CMAKE_STATIC_LIBRARY_SUFFIX})
#SET(COLD_BLAS_LIB ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}f2cblas${CMAKE_STATIC_LIBRARY_SUFFIX})

#SET(COLD_PETSC_LIB ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}petsc${CMAKE_SHARED_LIBRARY_SUFFIX})
SET(COLD_PETSC_LIB ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}petsc${CMAKE_STATIC_LIBRARY_SUFFIX})

#ADD_LIBRARY(COLD_PETSC_LIB STATIC IMPORTED)
#SET_TARGET_PROPERTIES(COLD_PETSC_LIB PROPERTIES IMPORTED_LOCATION ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}petsc${CMAKE_STATIC_LIBRARY_SUFFIX})



#LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_BLAS_LIB})
#LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_LAPACK_LIB})
LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_PETSC_LIB})
LIST(APPEND COLD_EXTERNAL_INCS ${COLD_PETSC_DIR}/include)
LIST(APPEND COLD_EXTERNAL_INCS ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/include)

#TARGET_INCLUDE_DIRECTORIES (COLD_PETSC_LIB PUBLIC ${COLD_PETSC_DIR}/include)
#TARGET_INCLUDE_DIRECTORIES (COLD_PETSC_LIB PUBLIC ${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/include)

INCLUDE_DIRECTORIES(${COLD_PETSC_DIR}/include)
INCLUDE_DIRECTORIES(${COLD_PETSC_DIR}/${COLD_PETSC_ARCH}/include)
LINK_DIRECTORIES(${COLD_PETCS_DIR}/${COLD_PETSC_ARCH}/lib)



##################################
# NIFTICLIB
##################################
SET(COLD_NIFTICLIB_DIR "${COLD_EXTERNAL_LIBDIR}/nifticlib")
SET(ENV{NIFTICLIB_DIR} "${COLD_NIFTICLIB_DIR}")

MESSAGE( STATUS "COLD_NIFTICLIB_DIR: " ${COLD_NIFTICLIB_DIR} )

IF(NOT COLD_NIFTI_LIBPRJ)

    EXTERNALPROJECT_ADD(COLD_NIFTICLIB_LIBPRJ
      #URL http://downloads.sourceforge.net/project/niftilib/nifticlib/nifticlib_2_0_0/nifticlib-2.0.0.tar.gz
      URL ${COLD_SOURCE_DIR}/external/nifticlib-2.0.0.tar.gz
      SOURCE_DIR ${COLD_NIFTICLIB_DIR}/src
      BINARY_DIR ${COLD_NIFTICLIB_DIR}/src
      TMP_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/nifticlib
      STAMP_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/nifticlib
      DOWNLOAD_DIR ${COLD_EXTERNAL_LIBDIR}/tmp/nifticlib
      INSTALL_DIR ${COLD_NIFTICLIB_DIR}/build
      CMAKE_ARGS -Wno-dev # suppress missing cmake_minimum_required() warning
      CMAKE_CACHE_ARGS "-DBUILD_SHARED_LIBS:BOOL=OFF"
                       "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
                       "-DCMAKE_INSTALL_PREFIX:PATH=${COLD_NIFTICLIB_DIR}/build"
      CMAKE_COMMAND cmake
      BUILD_COMMAND make
      INSTALL_COMMAND make install
)

ENDIF(NOT COLD_NIFTI_LIBPRJ)

# get the library
#FIND_LIBRARY(COLD_NIFTI_LIB NAMES libniftiio PATHS ${COLD_NIFTICLIB_DIR}/build/lib DOC "NIFTICLIB libs")

SET(COLD_NIFTIIO_LIB ${COLD_NIFTICLIB_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}niftiio${CMAKE_STATIC_LIBRARY_SUFFIX})
SET(COLD_NIFTICDF_LIB ${COLD_NIFTICLIB_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}nifticdf${CMAKE_STATIC_LIBRARY_SUFFIX})
SET(COLD_NIFTIZNZ_LIB ${COLD_NIFTICLIB_DIR}/build/lib/${CMAKE_STATIC_LIBRARY_PREFIX}znz${CMAKE_STATIC_LIBRARY_SUFFIX})

LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_NIFTICDF_LIB})
LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_NIFTIIO_LIB})
LIST(APPEND COLD_EXTERNAL_LIBS ${COLD_NIFTIZNZ_LIB})
LIST(APPEND COLD_EXTERNAL_INCS ${COLD_NIFTICLIB_DIR}/build/include/nifti)

LINK_DIRECTORIES(${COLD_NIFTICLIB_DIR}/build/lib)
INCLUDE_DIRECTORIES(${COLD_NIFTICLIB_DIR}/build/include/nifti)


SET(COLD_SRCS
${COLD_SOURCE_DIR}/src/ghost.cpp
${COLD_SOURCE_DIR}/src/interp3.cpp
${COLD_SOURCE_DIR}/src/Interp3_Plan.cpp
${COLD_SOURCE_DIR}/src/RegOpt.cpp
${COLD_SOURCE_DIR}/src/RegUtils.cpp
${COLD_SOURCE_DIR}/src/Optimizer.cpp
${COLD_SOURCE_DIR}/src/ReadWriteReg.cpp
${COLD_SOURCE_DIR}/src/TaoInterfaceRegistration.cpp
${COLD_SOURCE_DIR}/src/OptimizationProblemRegistration.cpp
${COLD_SOURCE_DIR}/src/LargeDeformationRegistration.cpp
${COLD_SOURCE_DIR}/src/OptimalControlRegistration.cpp
${COLD_SOURCE_DIR}/src/OptimalControlRegistrationIC.cpp
${COLD_SOURCE_DIR}/src/PreProcessingRegistration.cpp
${COLD_SOURCE_DIR}/src/RegularizationRegistration.cpp
${COLD_SOURCE_DIR}/src/SemiLagrangian.cpp
${COLD_SOURCE_DIR}/src/SynProbRegistration.cpp
${COLD_SOURCE_DIR}/src/VecField.cpp
)
#${COLD_SOURCE_DIR}/src/gpu_interp3.cpp
#${COLD_SOURCE_DIR}/src/SemiLagrangianGPU.cpp

LINK_DIRECTORIES( ${COLD_BINARY_DIR}/lib )
LINK_DIRECTORIES( ${OCREG_BINARY_DIR}/lib/coldreg )

# build library
#IF(BUILD_SHARED_LIBS)
#    ADD_LIBRARY(coldreg SHARED ${COLD_SRCS})
#ELSE(BUILD_SHARED_LIBS)
#    ADD_LIBRARY(coldreg STATIC ${COLD_SRCS})
#ENDIF(BUILD_SHARED_LIBS)

ADD_LIBRARY(coldreg ${COLD_SRCS})

# link libraries
TARGET_LINK_LIBRARIES( coldreg ${COLD_EXTERNAL_LIBS} )
MESSAGE(STATUS "external includes: ${COLD_NIFTICLIB_LIBPRJ}")

INSTALL(TARGETS coldreg DESTINATION lib)

