# prevent in-source builds
FUNCTION(CheckForInSourceBuild PROJECT_NAME PROJECT_VERSION)

  # make sure the user does not use symbolic links
  GET_FILENAME_COMPONENT(srcdir "${CMAKE_SOURCE_DIR}" REALPATH)
  GET_FILENAME_COMPONENT(bindir "${CMAKE_BINARY_DIR}" REALPATH)

  # prevent in-source builds
  IF("${srcdir}" STREQUAL "${bindir}")
    MESSAGE("")
    MESSAGE("///////////////////////////////////////////////////////////////////////" )
    MESSAGE(" ${PROJECT_NAME} should not be configured & built in the ${PROJECT_NAME} source directory" )
    MESSAGE(" You must run cmake in a build directory.")
    MESSAGE(" For example:")
    MESSAGE("")
    MESSAGE("     mkdir ${PROJECT_NAME}-v${PROJECT_VERSION}; cd ${PROJECT_NAME}-v${PROJECT_VERSION}")
    MESSAGE("")
    MESSAGE(" Check out source code in ${PROJECT_NAME}-v${PROJECT_VERSION}")
    MESSAGE("")
    MESSAGE("     mkdir ${PROJECT_NAME}-build")
    MESSAGE("")
    MESSAGE(" this will create the following directory structure")
    MESSAGE("")
    MESSAGE(" ${PROJECT_NAME}-v${PROJECT_VERSION}")
    MESSAGE("  +--${PROJECT_NAME}")
    MESSAGE("  +--${PROJECT_NAME}-build")
    MESSAGE("")
    MESSAGE(" You can proceed to configure and build as follows")
    MESSAGE("")
    MESSAGE("     cd ${PROJECT_NAME}-build")
    MESSAGE("     cmake ../${PROJECT_NAME}")
    MESSAGE("     make")
    MESSAGE("")
    MESSAGE(" NOTE: Given that you already tried to make an in-source build")
    MESSAGE("       CMake will have already created several files & directories")
    MESSAGE("       in your source tree.")
    MESSAGE("")
    MESSAGE(" The following command will show you all files not part of ${PROJECT_NAME}")
    MESSAGE("       cd ${PROJECT_NAME}-src/${PROJECT_NAME}")
    MESSAGE("       git status")
    MESSAGE("")
    MESSAGE(" WARNING: if you have added files to ${PROJECT_NAME} but not used git add")
    MESSAGE(" to add them to GIT's version control, this command will display them")
    MESSAGE(" along with the files CMake created during configuration. You will need")
    MESSAGE(" to either save them outside the ${PROJECT_NAME} source tree, or run git add")
    MESSAGE(" to let GIT know they are legitimate source files.")
    MESSAGE("///////////////////////////////////////////////////////////////////////" )
    MESSAGE("")
    MESSAGE(FATAL_ERROR "Quitting configuration")
  ENDIF()
ENDFUNCTION()

CheckForInSourceBuild(${CMAKE_PROJECT_NAME} ${COLD_VERSION})
